FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci --production

COPY . .

FROM node:20-alpine

RUN apk --no-cache add curl

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app ./

RUN addgroup -g 1001 -S appuser && \
    adduser -u 1001 -S appuser -G appuser
USER appuser

EXPOSE 8081

HEALTHCHECK CMD curl -f http://localhost:8081 || exit 1

CMD ["npm", "start"]
